/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesPremiumRouteImport } from './routes/packages.premium'
import { Route as PackagesCustomizedRouteImport } from './routes/packages.customized'
import { Route as PackagesClassicRouteImport } from './routes/packages.classic'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesPremiumRoute = PackagesPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesCustomizedRoute = PackagesCustomizedRouteImport.update({
  id: '/customized',
  path: '/customized',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesClassicRoute = PackagesClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => PackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/packages/classic': typeof PackagesClassicRoute
  '/packages/customized': typeof PackagesCustomizedRoute
  '/packages/premium': typeof PackagesPremiumRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/packages/classic': typeof PackagesClassicRoute
  '/packages/customized': typeof PackagesCustomizedRoute
  '/packages/premium': typeof PackagesPremiumRoute
  '/packages': typeof PackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/packages/classic': typeof PackagesClassicRoute
  '/packages/customized': typeof PackagesCustomizedRoute
  '/packages/premium': typeof PackagesPremiumRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/packages'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/packages/classic'
    | '/packages/customized'
    | '/packages/premium'
    | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/packages/classic'
    | '/packages/customized'
    | '/packages/premium'
    | '/packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/packages'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/packages/classic'
    | '/packages/customized'
    | '/packages/premium'
    | '/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/premium': {
      id: '/packages/premium'
      path: '/premium'
      fullPath: '/packages/premium'
      preLoaderRoute: typeof PackagesPremiumRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/customized': {
      id: '/packages/customized'
      path: '/customized'
      fullPath: '/packages/customized'
      preLoaderRoute: typeof PackagesCustomizedRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/classic': {
      id: '/packages/classic'
      path: '/classic'
      fullPath: '/packages/classic'
      preLoaderRoute: typeof PackagesClassicRouteImport
      parentRoute: typeof PackagesRoute
    }
  }
}

interface PackagesRouteChildren {
  PackagesClassicRoute: typeof PackagesClassicRoute
  PackagesCustomizedRoute: typeof PackagesCustomizedRoute
  PackagesPremiumRoute: typeof PackagesPremiumRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesClassicRoute: PackagesClassicRoute,
  PackagesCustomizedRoute: PackagesCustomizedRoute,
  PackagesPremiumRoute: PackagesPremiumRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
